/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FurutaPendulum_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};

/* FurutaPendulum_expl_vde_adj:(i0[4],i1[4],i2,i3[])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a01=(a00+a00);
  a02=5.0000000000000000e-01;
  a03=3.7053999999999999e-04;
  a04=2.;
  a05=arg[0]? arg[0][2] : 0;
  a06=(a04*a05);
  a07=sin(a06);
  a07=(a03*a07);
  a08=(a02*a07);
  a09=2.0999999999999999e-03;
  a10=sin(a05);
  a11=casadi_sq(a10);
  a11=(a03*a11);
  a09=(a09+a11);
  a11=(a03*a09);
  a12=4.4249084999999999e-04;
  a05=cos(a05);
  a13=(a12*a05);
  a14=casadi_sq(a13);
  a11=(a11-a14);
  a09=(a09/a11);
  a14=arg[1]? arg[1][3] : 0;
  a15=(a09*a14);
  a16=(a13/a11);
  a17=arg[1]? arg[1][1] : 0;
  a18=(a16*a17);
  a15=(a15-a18);
  a18=(a08*a15);
  a01=(a01*a18);
  a18=1.;
  a19=(a04*a00);
  a19=tanh(a19);
  a20=casadi_sq(a19);
  a20=(a18-a20);
  a21=1.0400000000000000e-02;
  a22=(a03/a11);
  a23=(a22*a17);
  a24=(a16*a14);
  a23=(a23-a24);
  a24=(a21*a23);
  a20=(a20*a24);
  a20=(a04*a20);
  a01=(a01-a20);
  a20=arg[0]? arg[0][3] : 0;
  a24=(a20*a23);
  a25=(a07*a24);
  a01=(a01-a25);
  a25=-1.6780769230769232e-03;
  a26=(a25*a23);
  a01=(a01+a26);
  a26=arg[1]? arg[1][0] : 0;
  a01=(a01+a26);
  if (res[0]!=0) res[0][1]=a01;
  a06=cos(a06);
  a01=casadi_sq(a00);
  a26=(a01*a15);
  a02=(a02*a26);
  a24=(a00*a24);
  a02=(a02-a24);
  a02=(a03*a02);
  a06=(a06*a02);
  a06=(a04*a06);
  a25=(a25*a00);
  a07=(a07*a00);
  a00=(a07*a20);
  a25=(a25-a00);
  a00=(a12*a10);
  a02=casadi_sq(a20);
  a24=(a00*a02);
  a25=(a25+a24);
  a24=4.9845923076923079e-02;
  a26=arg[2]? arg[2][0] : 0;
  a26=(a24*a26);
  a25=(a25+a26);
  a21=(a21*a19);
  a25=(a25-a21);
  a21=(a25*a14);
  a19=(a21/a11);
  a19=(a12*a19);
  a26=-2.6829999999999999e-05;
  a27=(a26*a20);
  a08=(a08*a01);
  a27=(a27+a08);
  a08=7.5418000000000002e-04;
  a01=(a04*a20);
  a01=tanh(a01);
  a28=(a08*a01);
  a27=(a27-a28);
  a28=9.8100000000000005e+00;
  a29=3.6419000000000000e-03;
  a30=(a29*a10);
  a30=(a28*a30);
  a27=(a27-a30);
  a30=(a27*a17);
  a31=(a30/a11);
  a13=(a13+a13);
  a16=(a16/a11);
  a21=(a16*a21);
  a09=(a09/a11);
  a27=(a27*a14);
  a09=(a09*a27);
  a21=(a21-a09);
  a16=(a16*a30);
  a21=(a21+a16);
  a22=(a22/a11);
  a25=(a25*a17);
  a22=(a22*a25);
  a21=(a21-a22);
  a13=(a13*a21);
  a31=(a31+a13);
  a31=(a12*a31);
  a19=(a19+a31);
  a19=(a10*a19);
  a06=(a06+a19);
  a02=(a02*a23);
  a12=(a12*a02);
  a28=(a28*a15);
  a29=(a29*a28);
  a12=(a12-a29);
  a10=(a10+a10);
  a27=(a27/a11);
  a21=(a03*a21);
  a27=(a27+a21);
  a03=(a03*a27);
  a10=(a10*a03);
  a12=(a12+a10);
  a05=(a05*a12);
  a06=(a06+a05);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[1]? arg[1][2] : 0;
  a01=casadi_sq(a01);
  a18=(a18-a01);
  a08=(a08*a15);
  a18=(a18*a08);
  a04=(a04*a18);
  a06=(a06-a04);
  a26=(a26*a15);
  a06=(a06+a26);
  a20=(a20+a20);
  a00=(a00*a23);
  a20=(a20*a00);
  a06=(a06+a20);
  a07=(a07*a23);
  a06=(a06-a07);
  if (res[0]!=0) res[0][3]=a06;
  a24=(a24*a23);
  if (res[0]!=0) res[0][4]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FurutaPendulum_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int FurutaPendulum_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real FurutaPendulum_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FurutaPendulum_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FurutaPendulum_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FurutaPendulum_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FurutaPendulum_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
