/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FurutaPendulum_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};

/* FurutaPendulum_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=3.7053999999999999e-04;
  a02=2.0999999999999999e-03;
  a03=arg[0]? arg[0][2] : 0;
  a04=sin(a03);
  a05=casadi_sq(a04);
  a05=(a01*a05);
  a02=(a02+a05);
  a05=(a01*a02);
  a06=4.4249084999999999e-04;
  a07=cos(a03);
  a08=(a06*a07);
  a09=casadi_sq(a08);
  a05=(a05-a09);
  a09=(a01/a05);
  a10=-1.6780769230769232e-03;
  a11=(a10*a00);
  a12=2.;
  a03=(a12*a03);
  a13=sin(a03);
  a13=(a01*a13);
  a14=(a13*a00);
  a15=arg[0]? arg[0][3] : 0;
  a16=(a14*a15);
  a11=(a11-a16);
  a16=(a06*a04);
  a17=casadi_sq(a15);
  a18=(a16*a17);
  a11=(a11+a18);
  a18=4.9845923076923079e-02;
  a19=arg[3]? arg[3][0] : 0;
  a19=(a18*a19);
  a11=(a11+a19);
  a19=1.0400000000000000e-02;
  a20=(a12*a00);
  a20=tanh(a20);
  a21=(a19*a20);
  a11=(a11-a21);
  a21=(a09*a11);
  a22=(a08/a05);
  a23=-2.6829999999999999e-05;
  a24=(a23*a15);
  a25=5.0000000000000000e-01;
  a26=(a25*a13);
  a27=casadi_sq(a00);
  a28=(a26*a27);
  a24=(a24+a28);
  a28=7.5418000000000002e-04;
  a29=(a12*a15);
  a29=tanh(a29);
  a30=(a28*a29);
  a24=(a24-a30);
  a30=9.8100000000000005e+00;
  a31=3.6419000000000000e-03;
  a32=(a31*a04);
  a32=(a30*a32);
  a24=(a24-a32);
  a32=(a22*a24);
  a21=(a21-a32);
  if (res[0]!=0) res[0][1]=a21;
  if (res[0]!=0) res[0][2]=a15;
  a02=(a02/a05);
  a21=(a02*a24);
  a32=(a22*a11);
  a21=(a21-a32);
  if (res[0]!=0) res[0][3]=a21;
  a21=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a21;
  a32=(a10*a21);
  a03=cos(a03);
  a33=arg[1]? arg[1][2] : 0;
  a34=(a12*a33);
  a34=(a03*a34);
  a34=(a01*a34);
  a35=(a00*a34);
  a36=(a13*a21);
  a35=(a35+a36);
  a35=(a15*a35);
  a36=arg[1]? arg[1][3] : 0;
  a37=(a14*a36);
  a35=(a35+a37);
  a32=(a32-a35);
  a35=(a07*a33);
  a37=(a06*a35);
  a37=(a17*a37);
  a38=(a15+a15);
  a39=(a38*a36);
  a39=(a16*a39);
  a37=(a37+a39);
  a32=(a32+a37);
  a37=1.;
  a20=casadi_sq(a20);
  a20=(a37-a20);
  a39=(a12*a21);
  a39=(a20*a39);
  a39=(a19*a39);
  a32=(a32-a39);
  a39=(a09*a32);
  a40=(a09/a05);
  a41=(a04+a04);
  a42=(a41*a35);
  a42=(a01*a42);
  a43=(a01*a42);
  a08=(a08+a08);
  a33=(a04*a33);
  a33=(a06*a33);
  a44=(a08*a33);
  a43=(a43+a44);
  a44=(a40*a43);
  a44=(a11*a44);
  a39=(a39-a44);
  a44=(a23*a36);
  a34=(a25*a34);
  a34=(a27*a34);
  a45=(a00+a00);
  a21=(a45*a21);
  a21=(a26*a21);
  a34=(a34+a21);
  a44=(a44+a34);
  a29=casadi_sq(a29);
  a37=(a37-a29);
  a29=(a12*a36);
  a29=(a37*a29);
  a29=(a28*a29);
  a44=(a44-a29);
  a35=(a31*a35);
  a35=(a30*a35);
  a44=(a44-a35);
  a35=(a22*a44);
  a33=(a33/a05);
  a29=(a22/a05);
  a34=(a29*a43);
  a33=(a33+a34);
  a34=(a24*a33);
  a35=(a35-a34);
  a39=(a39-a35);
  if (res[1]!=0) res[1][1]=a39;
  if (res[1]!=0) res[1][2]=a36;
  a42=(a42/a05);
  a36=(a02/a05);
  a43=(a36*a43);
  a42=(a42-a43);
  a42=(a24*a42);
  a44=(a02*a44);
  a42=(a42+a44);
  a32=(a22*a32);
  a33=(a11*a33);
  a32=(a32-a33);
  a42=(a42-a32);
  if (res[1]!=0) res[1][3]=a42;
  a42=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][4]=a42;
  a32=(a10*a42);
  a33=arg[1]? arg[1][6] : 0;
  a44=(a12*a33);
  a44=(a03*a44);
  a44=(a01*a44);
  a43=(a00*a44);
  a39=(a13*a42);
  a43=(a43+a39);
  a43=(a15*a43);
  a39=arg[1]? arg[1][7] : 0;
  a35=(a14*a39);
  a43=(a43+a35);
  a32=(a32-a43);
  a43=(a07*a33);
  a35=(a06*a43);
  a35=(a17*a35);
  a34=(a38*a39);
  a34=(a16*a34);
  a35=(a35+a34);
  a32=(a32+a35);
  a35=(a12*a42);
  a35=(a20*a35);
  a35=(a19*a35);
  a32=(a32-a35);
  a35=(a09*a32);
  a34=(a41*a43);
  a34=(a01*a34);
  a21=(a01*a34);
  a33=(a04*a33);
  a33=(a06*a33);
  a46=(a08*a33);
  a21=(a21+a46);
  a46=(a40*a21);
  a46=(a11*a46);
  a35=(a35-a46);
  a46=(a23*a39);
  a44=(a25*a44);
  a44=(a27*a44);
  a42=(a45*a42);
  a42=(a26*a42);
  a44=(a44+a42);
  a46=(a46+a44);
  a44=(a12*a39);
  a44=(a37*a44);
  a44=(a28*a44);
  a46=(a46-a44);
  a43=(a31*a43);
  a43=(a30*a43);
  a46=(a46-a43);
  a43=(a22*a46);
  a33=(a33/a05);
  a44=(a29*a21);
  a33=(a33+a44);
  a44=(a24*a33);
  a43=(a43-a44);
  a35=(a35-a43);
  if (res[1]!=0) res[1][5]=a35;
  if (res[1]!=0) res[1][6]=a39;
  a34=(a34/a05);
  a21=(a36*a21);
  a34=(a34-a21);
  a34=(a24*a34);
  a46=(a02*a46);
  a34=(a34+a46);
  a32=(a22*a32);
  a33=(a11*a33);
  a32=(a32-a33);
  a34=(a34-a32);
  if (res[1]!=0) res[1][7]=a34;
  a34=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a34;
  a32=(a10*a34);
  a33=arg[1]? arg[1][10] : 0;
  a46=(a12*a33);
  a46=(a03*a46);
  a46=(a01*a46);
  a21=(a00*a46);
  a39=(a13*a34);
  a21=(a21+a39);
  a21=(a15*a21);
  a39=arg[1]? arg[1][11] : 0;
  a35=(a14*a39);
  a21=(a21+a35);
  a32=(a32-a21);
  a21=(a07*a33);
  a35=(a06*a21);
  a35=(a17*a35);
  a43=(a38*a39);
  a43=(a16*a43);
  a35=(a35+a43);
  a32=(a32+a35);
  a35=(a12*a34);
  a35=(a20*a35);
  a35=(a19*a35);
  a32=(a32-a35);
  a35=(a09*a32);
  a43=(a41*a21);
  a43=(a01*a43);
  a44=(a01*a43);
  a33=(a04*a33);
  a33=(a06*a33);
  a42=(a08*a33);
  a44=(a44+a42);
  a42=(a40*a44);
  a42=(a11*a42);
  a35=(a35-a42);
  a42=(a23*a39);
  a46=(a25*a46);
  a46=(a27*a46);
  a34=(a45*a34);
  a34=(a26*a34);
  a46=(a46+a34);
  a42=(a42+a46);
  a46=(a12*a39);
  a46=(a37*a46);
  a46=(a28*a46);
  a42=(a42-a46);
  a21=(a31*a21);
  a21=(a30*a21);
  a42=(a42-a21);
  a21=(a22*a42);
  a33=(a33/a05);
  a46=(a29*a44);
  a33=(a33+a46);
  a46=(a24*a33);
  a21=(a21-a46);
  a35=(a35-a21);
  if (res[1]!=0) res[1][9]=a35;
  if (res[1]!=0) res[1][10]=a39;
  a43=(a43/a05);
  a44=(a36*a44);
  a43=(a43-a44);
  a43=(a24*a43);
  a42=(a02*a42);
  a43=(a43+a42);
  a32=(a22*a32);
  a33=(a11*a33);
  a32=(a32-a33);
  a43=(a43-a32);
  if (res[1]!=0) res[1][11]=a43;
  a43=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a43;
  a32=(a10*a43);
  a33=arg[1]? arg[1][14] : 0;
  a42=(a12*a33);
  a42=(a03*a42);
  a42=(a01*a42);
  a44=(a00*a42);
  a39=(a13*a43);
  a44=(a44+a39);
  a44=(a15*a44);
  a39=arg[1]? arg[1][15] : 0;
  a35=(a14*a39);
  a44=(a44+a35);
  a32=(a32-a44);
  a44=(a07*a33);
  a35=(a06*a44);
  a35=(a17*a35);
  a21=(a38*a39);
  a21=(a16*a21);
  a35=(a35+a21);
  a32=(a32+a35);
  a35=(a12*a43);
  a35=(a20*a35);
  a35=(a19*a35);
  a32=(a32-a35);
  a35=(a09*a32);
  a21=(a41*a44);
  a21=(a01*a21);
  a46=(a01*a21);
  a33=(a04*a33);
  a33=(a06*a33);
  a34=(a08*a33);
  a46=(a46+a34);
  a34=(a40*a46);
  a34=(a11*a34);
  a35=(a35-a34);
  a34=(a23*a39);
  a42=(a25*a42);
  a42=(a27*a42);
  a43=(a45*a43);
  a43=(a26*a43);
  a42=(a42+a43);
  a34=(a34+a42);
  a42=(a12*a39);
  a42=(a37*a42);
  a42=(a28*a42);
  a34=(a34-a42);
  a44=(a31*a44);
  a44=(a30*a44);
  a34=(a34-a44);
  a44=(a22*a34);
  a33=(a33/a05);
  a42=(a29*a46);
  a33=(a33+a42);
  a42=(a24*a33);
  a44=(a44-a42);
  a35=(a35-a44);
  if (res[1]!=0) res[1][13]=a35;
  if (res[1]!=0) res[1][14]=a39;
  a21=(a21/a05);
  a46=(a36*a46);
  a21=(a21-a46);
  a21=(a24*a21);
  a34=(a02*a34);
  a21=(a21+a34);
  a32=(a22*a32);
  a33=(a11*a33);
  a32=(a32-a33);
  a21=(a21-a32);
  if (res[1]!=0) res[1][15]=a21;
  a21=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a21;
  a32=(a18*a09);
  a10=(a10*a21);
  a33=arg[2]? arg[2][2] : 0;
  a34=(a12*a33);
  a03=(a03*a34);
  a03=(a01*a03);
  a00=(a00*a03);
  a13=(a13*a21);
  a00=(a00+a13);
  a15=(a15*a00);
  a00=arg[2]? arg[2][3] : 0;
  a14=(a14*a00);
  a15=(a15+a14);
  a10=(a10-a15);
  a07=(a07*a33);
  a15=(a06*a07);
  a17=(a17*a15);
  a38=(a38*a00);
  a16=(a16*a38);
  a17=(a17+a16);
  a10=(a10+a17);
  a17=(a12*a21);
  a20=(a20*a17);
  a19=(a19*a20);
  a10=(a10-a19);
  a09=(a09*a10);
  a41=(a41*a07);
  a41=(a01*a41);
  a01=(a01*a41);
  a04=(a04*a33);
  a06=(a06*a04);
  a08=(a08*a06);
  a01=(a01+a08);
  a40=(a40*a01);
  a40=(a11*a40);
  a09=(a09-a40);
  a23=(a23*a00);
  a25=(a25*a03);
  a27=(a27*a25);
  a45=(a45*a21);
  a26=(a26*a45);
  a27=(a27+a26);
  a23=(a23+a27);
  a12=(a12*a00);
  a37=(a37*a12);
  a28=(a28*a37);
  a23=(a23-a28);
  a31=(a31*a07);
  a30=(a30*a31);
  a23=(a23-a30);
  a30=(a22*a23);
  a06=(a06/a05);
  a29=(a29*a01);
  a06=(a06+a29);
  a29=(a24*a06);
  a30=(a30-a29);
  a09=(a09-a30);
  a32=(a32+a09);
  if (res[2]!=0) res[2][1]=a32;
  if (res[2]!=0) res[2][2]=a00;
  a41=(a41/a05);
  a36=(a36*a01);
  a41=(a41-a36);
  a24=(a24*a41);
  a02=(a02*a23);
  a24=(a24+a02);
  a10=(a22*a10);
  a11=(a11*a06);
  a10=(a10-a11);
  a24=(a24-a10);
  a18=(a18*a22);
  a24=(a24-a18);
  if (res[2]!=0) res[2][3]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void FurutaPendulum_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FurutaPendulum_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int FurutaPendulum_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real FurutaPendulum_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FurutaPendulum_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FurutaPendulum_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FurutaPendulum_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FurutaPendulum_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int FurutaPendulum_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
